import type { BusinessContext, CampaignFull, ReleaseFull, TrackFull } from "@/lib/types";

let n = 0;
const uid = () => `00000000-0000-4000-8000-${String(++n).padStart(12, "0")}`;
const now = new Date("2026-09-01T10:00:00Z");

export function makeTrack(over: Partial<TrackFull> = {}): TrackFull {
  return {
    id: uid(),
    userId: "u1",
    projectCode: `MF-${n}`,
    title: "Nightfall",
    primaryArtist: "MayFar",
    featuredArtists: [],
    genre: "Melodic Techno",
    subgenre: null,
    bpm: 124,
    musicalKey: "A minor",
    mood: "Dark",
    language: "Instrumental",
    durationSec: 390,
    isrc: null,
    lyrics: null,
    productionNotes: null,
    explicit: "no",
    status: "Finished",
    workflowStage: "Mastering",
    plannedReleaseDate: null,
    actualReleaseDate: null,
    hasCollaborators: "no",
    isDemo: false,
    createdAt: now,
    updatedAt: now,
    versions: [],
    collaborators: [],
    splits: [],
    rights: null,
    feedback: [],
    releaseIds: [],
    ...over,
  };
}

export function makeRelease(over: Partial<ReleaseFull> = {}): ReleaseFull {
  return {
    id: uid(),
    userId: "u1",
    title: "Nightfall",
    releaseType: "single",
    primaryArtist: "MayFar",
    featuredArtists: [],
    releaseDate: "2026-10-30",
    releaseDateConfirmed: false,
    submissionDeadline: null,
    status: "Planning",
    distributor: null,
    upc: null,
    genre: "Melodic Techno",
    language: "Instrumental",
    explicit: "no",
    strategy: null,
    coverDocumentId: null,
    coverApproved: false,
    preSaveUrl: null,
    smartLinkUrl: null,
    promoLinks: {},
    preferences: { campaign: true },
    notes: null,
    projectId: null,
    isDemo: false,
    createdAt: now,
    updatedAt: now,
    trackIds: [],
    checklist: [],
    execution: [],
    reviews: [],
    ...over,
  };
}

export function makeCampaign(over: Partial<CampaignFull> = {}): CampaignFull {
  return {
    id: uid(),
    userId: "u1",
    name: "Nightfall launch",
    releaseId: null,
    trackId: null,
    template: "pre_release",
    objective: "Promote a release",
    targetAudience: null,
    budget: null,
    currency: "EUR",
    startDate: "2026-10-01",
    endDate: "2026-11-15",
    channels: [],
    creativeDirection: null,
    message: null,
    contentStrategy: null,
    outreachStrategy: null,
    successMetrics: null,
    status: "Planning",
    results: null,
    notes: null,
    isDemo: false,
    createdAt: now,
    updatedAt: now,
    ads: [],
    ...over,
  };
}

export function makeContext(over: Partial<BusinessContext> = {}): BusinessContext {
  return {
    today: "2026-09-27",
    userId: "u1",
    settings: {
      userId: "u1",
      currency: "EUR",
      timezone: "Europe/Berlin",
      dateFormat: "",
      language: "en",
      theme: "dark",
      notificationPrefs: {},
      customStatuses: {},
      trackWorkflow: [],
      updatedAt: now,
    },
    profile: {
      id: "p1",
      userId: "u1",
      artistName: null,
      legalName: null,
      bio: null,
      country: null,
      city: null,
      contactEmail: null,
      website: null,
      imageUrl: null,
      logoUrl: null,
      genres: [],
      artisticDirection: null,
      brandConcept: null,
      brandPhrase: null,
      visualIdentity: null,
      languages: [],
      careerStage: null,
      goals: {},
      musicIdentity: {},
      catalogSummary: {},
      business: {},
      team: {},
      workflowPrefs: {},
      onboardingSteps: {},
      onboardingCompletedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    platformLinks: [],
    goals: [],
    tracks: [],
    releases: [],
    campaigns: [],
    content: [],
    tasks: [],
    projects: [],
    contacts: [],
    transactions: [],
    budgets: [],
    documents: [],
    phaseStates: [],
    infoMeta: [],
    analyticsCount: 0,
    ...over,
  };
}

export function split(trackId: string, rightType: "composition" | "master", holderName: string, percentage: number, confirmed = true) {
  return {
    id: uid(),
    userId: "u1",
    trackId,
    rightType,
    holderName,
    contactId: null,
    role: null,
    percentage,
    confirmed,
    agreementDocumentId: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  };
}

export function master(trackId: string, approved = true) {
  return {
    id: uid(),
    userId: "u1",
    trackId,
    kind: "master",
    label: "Master v1",
    documentId: null,
    externalUrl: null,
    notes: null,
    approved,
    approvedAt: approved ? now : null,
    createdAt: now,
  };
}

export function rights(trackId: string, over: Record<string, unknown> = {}) {
  return {
    id: uid(),
    userId: "u1",
    trackId,
    samplesUsed: "none",
    sampleDetails: null,
    sampleLicenseStatus: "not_needed",
    agreementStatus: "not_needed",
    copyrightRegistration: "not_started",
    proRegistration: "not_started",
    royaltyCollection: "not_started",
    collectionServices: null,
    openQuestions: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
    ...over,
  };
}
